version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 80:80
  api:
    build: ./api
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - PORT=4000
      - NODE_ENV=production
    expose:
      - 4000
    ports:
      - 4000:4000
