version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    ports:
      - 80:3000
    depends_on:
      - api
  api:
    build: ./api
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - PORT=4000
      - NODE_ENV=development
    expose:
      - 4000
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    expose:
      - 6379
